server:
  port: 8081
spring:
  application:
    name: "user"
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: ''
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
  sql:
    init:
      mode: always
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB